spring:
  data:
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 5
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: validate
    database: postgresql
  flyway:
    enabled: true
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    baseline-on-migrate: true
    baseline-description: 'init'
    baseline-version: 0

jwt:
  expirationTime: 86_400_000 # 24 hours in milliseconds
  secretKey: strongsecretkey2323232egfewgwerggergergrferfe3!

system-configuration:
  public-endpoints: /api/auth/**, /swagger-ui/**, /v3/api-docs/**, /error
