spring:
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: validate
    database: postgresql
  flyway:
    enabled: true
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    baseline-on-migrate: true
    baseline-description: 'init'
    baseline-version: 0

system-configuration:
  public-endpoints: /api/auth/register, /swagger-ui/**, /v3/api-docs/**
